---

- name: check if docker package is installed
  package:
    name: "docker-ce"
    state: present
  check_mode: true
  register: package_check_docker
  ignore_errors: yes

- name: get docker service status
  shell: 'systemctl is-active docker'
  register: docker_service_status
  ignore_errors: yes
  changed_when: false
  when: package_check_docker is succeeded

- name: get docker version
  shell: "docker version --format '{{ '{{' }}.Server.Version{{ '}}' }}'" 
  register: docker_version
  changed_when: false
  when: package_check_docker is succeeded

- name: check if sshguard package is installed
  package:
    name: "sshguard"
    state: present
  check_mode: true
  register: package_check_sshguard
  ignore_errors: yes

- import_tasks: install.yml

- import_tasks: service.yml

- import_tasks: config.yml

- import_tasks: manage.yml

- import_tasks: ufw-docker-automated.yml
  when: package_check_docker is succeeded and docker_version.stdout is version('20.10', '>=')

- import_tasks: sshguard.yml
  when: package_check_sshguard is succeeded
