---

- name: "check if docker is installed"
  shell: 'dpkg -s docker-ce'
  ignore_errors: yes
  changed_when: false
  failed_when: false
  register: package_check_docker

- name: "get docker service status"
  shell: 'systemctl is-active docker'
  register: docker_service_status
  ignore_errors: yes
  changed_when: false
  when: package_check_docker.rc == 0

- name: "get docker version"
  shell: "docker version --format '{{ '{{' }}.Server.Version{{ '}}' }}'" 
  register: docker_version
  changed_when: false
  when: package_check_docker.rc == 0

- name: "check if sshguard is installed"
  shell: 'dpkg -s sshguard'
  ignore_errors: yes
  changed_when: false
  failed_when: false
  register: package_check_sshguard

- import_tasks: install.yml

- import_tasks: service.yml

- import_tasks: config.yml

- import_tasks: manage.yml

- import_tasks: ufw-docker-automated.yml
  when: package_check_docker.rc == 0 and docker_version.stdout is version('20.10', '>=')

- import_tasks: sshguard.yml
  when: package_check_sshguard.rc == 0
