---
- name: download ufw-docker script
  get_url:
    url: https://github.com/chaifeng/ufw-docker/raw/master/ufw-docker
    dest: /usr/local/bin/ufw-docker
    mode: '0750'

- name: install special rules for ufw-docker
  template:
    src: "after.rules.j2"
    dest: "/etc/ufw/after.rules"
  register: after_rules

- name: add customization script to cleanup DOCKER-USER chain else ufw cannot be enabled after disabling
  template:
    src: "before.init.j2"
    dest: "/etc/ufw/before.init"
    mode: '0750'
  register: before_init

- name: restart service ufw
  systemd:
    state: restarted
    name: ufw
  when: after_rules.changed

- name: copy ufw-docker-automated binary
  copy:
    src: ../files/ufw-docker-automated
    dest: /usr/local/bin/ufw-docker-automated
    owner: root
    group: root
    mode: '0755'

- name: add service file of ufw-docker-automated to systemd
  template:
    src: "ufw-docker-automated.service.j2"
    dest: "/etc/systemd/system/ufw-docker-automated.service"

- name: start service ufw-docker-automated, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: ufw-docker-automated
  when: docker_service_status.rc == 0
  changed_when: false
